### ISSUE TITLE
Question about this mod

### ISSUE THREAD

**Issue by EGOIST1372** [Keksuccino/FancyMenu-Video-Extension#1]
Hi
does this mean we can have cave animation in fancy menu without lag and hiccups here and there? (I even turned on cache option that was on settings in fancy menu that make loading screen freeze at the end so it loads the frame before hand and it still lags and hiccups)
and if yes then we can use that without any lag then it would be great that you put that cave animation video alongside this mod in mod description page.
also I'm looking forward for fabric version of it in 1.18.2 so I can try it myself to test this theory.
thanks so much for your great mods <3

**Comment by Keksuccino** [comment]
Well yes, as soon as it works as intended, you will be able to use the real video version of the cave animation :) But it's currently not ready for general use yet. It only works on Windows.

**Comment by EGOIST1372** [comment]
Great news
I'm a windows user so it would be no problem for me at least :D

**Comment by EGOIST1372** [comment]
@Keksuccino I saw a fabric version released 2 days ago
can you put cave animations video in the description and demonstrate with a video how to use it?

**Comment by Gai-fan** [comment]
we need 1.18.2 fabric，please
